version: 2
updates:
  - package-ecosystem: cargo
    directory: "/mail_lib_types"
    schedule:
      interval: daily
  - package-ecosystem: cargo
    directory: "/"
    schedule:
      interval: daily
  - package-ecosystem: cargo
    directory: "/smtp_lib"
    schedule:
      interval: daily
